name: CI
on:
  push:
    branches: [main, workflow]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Go to client Folder
      - run: cd client
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/packeges-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm ci
      - name: Build
        if: github.event_name == 'push'
        run: npm run build
      - name: Upload Build Folder
        uses: actions/upload-artifact@v1
        with:
          name: code-build
          path: build
      - name: Copy
        uses: andstor/copycat-action@v3
        env:
          GITHUB_REF: ${{ toJSON(github.head_ref) }}
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: client/dist
          src_branch: main
          dst_path: /dynophores_webclient/
          dst_owner: nadja-mansurov
          dst_repo_name: nadja-mansurov.github.io
          dst_branch: gh-pages
          clean: true