name: CI
on:
  push:
    branches: [main, workflow]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/packeges-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm ci & npm build
      
      - name: Copy
        uses: andstor/copycat-action@v3
        env:
          GITHUB_REF: $GITHUB_REF
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: client/dist
          src_branch: ${{ GITHUB_REF }}
          dst_path: /dynophores_webclient/
          dst_owner: nadja-mansurov
          dst_repo_name: nadja-mansurov.github.io
          dst_branch: gh-pages
          clean: true