name: CI
on:
  push:
    branches: [main, workflow]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/packeges-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install 
        run: |
          cd client  
          npm ci
      - name: Build
        run: |
          cd client
          npm run buildaot
      - name: Upload Build Folder
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v1
        with:
          name: code-build
          path: client/dist/dynophores_webclient
      - name: Copy
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: client/dist/dynophores_webclient/.
          src_branch: workflow
          dst_path: /dynophores_webclient/
          dst_owner: nadja-mansurov
          dst_repo_name: nadja-mansurov.github.io
          dst_branch: gh-pages