
name: CI


on:
  push:
    branches: [ feature/#1_add_cypress ]
  #pull_request:
    #branches: [ main ]

  
  workflow_dispatch:


jobs:
  cypress-run:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  #  steps:
  #    - name: Checkout
  #    - uses: actions/checkout@v2

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
  #    - name: Build Prod App With No Service worker
  #      run: |
        #  ng build --c=production-no-sw
  #    - name: Run Cypress Test Suite
  #      run: |
        #  npm run ci:cy-run
      #- uses: nadja-mansurov/dyno_webapp@v2
      #  with:
      #    working-directory: client
      #    build: npx cypress info
        
