
name: CI

on:
  push:
    branches: 
      - feature/#1_add_cypress

jobs:
  install:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2

  install-cy:
    runs-on: ubuntu-latest
    needs: install
    steps: 
    - name: Install cy
      run: npm install cypress

  project_start:
    runs-on: ubuntu-latest
    needs: install-cy
    steps: 
    - name: npm install
      run: npm install    
    - name: Project_start
      run: npm buildaot

  cypress_run_test:
    runs-on: ubuntu-latest
    needs: project_start
    steps:     
    - name: Cypress_run_test 
      run: npx cypress run 

    #steps:
    #- name: Cypress run
    #- uses: actions/checkout@v2
    #- uses: cypress-io/github-action@v2.2.7

    #steps:
    #- uses: main
    #- run: npm run build
    #- run: npm run start
    #- run: 'http://localhost:4200/'
    #- run: baseUrl=http://localhost:4200
    #- run: |
     #     cypress/integration/checkboxes.spec.ts
     #     cypress/integration/displayButtons.spec.ts







        

   
      
        
