
  name: CI

  on: [push]
  

  jobs:
    test:
      name: Running Unit Tests
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2 
        - name: Setup node   
          uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: Install npm
          run: npm install
        - name: Unit Test
          run: npm test     
        







        

   
      
        
