
name: CI


on:
  push:
    branches: [ feature/#1_add_cypress ]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
    - uses: actions/checkout@v2

    - name: Cypress run
    - uses: cypress-io/github-action@v2.2.7
      with:
        browser: chrome

   
      
        
