
name: CI


on:
  push:
    branches: [ feature/#1_add_cypress ]
  #pull_request:
    #branches: [ main ]

  
  workflow_dispatch:


jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: cypress-io/github-action@v2

    - run: ng build --c=production-no-sw
    - run: npm run ci:cy-run
      
        
