
name: CI


on:
  push:
    branches: 
      - feature/#1_add_cypress

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    #- uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      run: npm run build
      # run: npm run start

    #steps:
    #- name: Cypress run
    #- uses: cypress-io/github-action@v2.2.7

    #steps:
    #- uses: main
    #- run: npm run build
    #- run: npm run start
    #- run: 'http://localhost:4200/'
    #- run: baseUrl=http://localhost:4200
    #- run: |
     #     cypress/integration/checkboxes.spec.ts
     #     cypress/integration/displayButtons.spec.ts







        

   
      
        
