
name: CI


on:
  push:
    branches: [ feature/#1_add_cypress ]
  #pull_request:
    #branches: [ main ]

  
  workflow_dispatch:


jobs:
  cypress-run:
    runs-on: ubuntu-20.04

   
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Build Prod App With No Service worker
        run: |
          ng build --c=production-no-sw
      - name: Run Cypress Test Suite
        run: |
          npm run ci:cy-run
      #- uses: nadja-mansurov/dyno_webapp@v2
      #  with:
      #    working-directory: client
      #    build: npx cypress info
        
