
  name: CI

  on: [push]
  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2 
        - name: Setup node   
          uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: Install npm
          run: npm install -g bats
        - name: Software version
          run: bats -v 
    unit_test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2    
        - name:uses: Adzz/jest_test_action@v1.0.0
          with:
            command: npm test
                
        







        

   
      
        
